# Generated by Django 5.1.6 on 2025-02-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authoer',
            new_name='author',
        ),
    ]
